### ISSUE TITLE
Generator produces invalid code with function that returns an array using IVI-dance size mechanism

### ISSUE THREAD

**Issue by marcoskirsch** [ni/nimi-python#537]
This was most likely introduced with https://github.com/ni/nimi-python/commit/36f11f13ce8ec78be06b93b1ac7333bc366b866c

However, we had no instances in our drivers, nor did we have NI-FAKE coverage for this case so it went unnoticed. This is now affecting niFgen_GetFIRFilterCoefficients.

I have added a function that illustrates this in NI-FAKE in branch https://github.com/ni/nimi-python/tree/get_array_ivi_dance . I still have to add a unit test, but just generating the function is enough to fail flake8.

**Comment by marcoskirsch** [comment]
mock_helper.py.mako is also incorrect. This is what I get for this function:

```
    def niFake_GetArrayUsingIVIDance(self, vi, array_size, array_out):  # noqa: N802
        if self._defaults['GetArrayUsingIVIDance']['return'] != 0:
            return self._defaults['GetArrayUsingIVIDance']['return']
        if self._defaults['GetArrayUsingIVIDance']['arrayOut'] is None:
            raise MockFunctionCallError("niFake_GetArrayUsingIVIDance", param='arrayOut')
        if array_size.value == 0:
            return len(self._defaults['GetArrayUsingIVIDance']['arrayOut'])
        array_out.value = self._defaults['GetArrayUsingIVIDance']['arrayOut'].encode('ascii')
        return self._defaults['GetArrayUsingIVIDance']['return']
```

The problem is in `array_out.value = self._defaults['GetArrayUsingIVIDance']['arrayOut'].encode('ascii')`:

`E       AttributeError: 'list' object has no attribute 'encode'`

It is getting treated the same as a string.
