### ISSUE TITLE
test_system_nidmm.py's test_acquisition is broken

### ISSUE THREAD

**Issue by marcoskirsch** [ni/nimi-python#93]
```
src\nidmm\system_tests\test_system_nidmm.py:108: NameError
______________________________ test_acquisition _______________________________

device_info = {'name': '4070', 'sn': '00D82BA5'}

    def test_acquisition(device_info):
        with nidmm.Session(device_info['name']) as session:
            session.configure_measurement_digits(nidmm.Function.DC_CURRENT, 1, 5.5)
>           with session.acquisition:
E           AttributeError: 'Session' object has no attribute 'acquisition'

src\nidmm\system_tests\test_system_nidmm.py:122: AttributeError
===================== 4 failed, 7 passed in 4.92 seconds ======================
```

**Comment by marcoskirsch** [comment]
Broken in https://github.com/ni/nimi-python/pull/89
